### ISSUE TITLE
Component AbstractNeoServer$ServerComponentsLifecycleAdapter failed to start

### ISSUE THREAD

**Issue by Wenzel** [neo4j-graphql/neo4j-graphql#127]
Hi,

The latest version of the plugin from `master` is crashing `neo4j`:

~~~
2018-07-24 13:07:46.803+0000 INFO  ======== Neo4j 3.4.0 ========
2018-07-24 13:07:46.829+0000 INFO  Starting...
2018-07-24 13:07:49.305+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2018-07-24 13:07:52.668+0000 INFO  Started.
2018-07-24 13:07:52.842+0000 INFO  Mounted unmanaged extension [org.neo4j.graphql] at [/graphql]
2018-07-24 13:07:53.453+0000 INFO  Stopping...
2018-07-24 13:07:53.516+0000 INFO  Stopped.
2018-07-24 13:07:53.518+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@7d836c4a' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.proc.ProcedureSignature". Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@7d836c4a' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.proc.ProcedureSignature".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@7d836c4a' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.proc.ProcedureSignature".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@7d836c4a' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.proc.ProcedureSignature".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/api/proc/ProcedureSignature
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at com.sun.jersey.core.reflection.MethodList.getMethods(MethodList.java:77)
	at com.sun.jersey.core.reflection.MethodList.<init>(MethodList.java:64)
	at com.sun.jersey.core.reflection.MethodList.<init>(MethodList.java:60)
	at com.sun.jersey.server.impl.modelapi.annotation.IntrospectionModeller.createResource(IntrospectionModeller.java:118)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.getAbstractResource(WebApplicationImpl.java:769)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.createAbstractResourceModelStructures(WebApplicationImpl.java:1595)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1356)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:665)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:423)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:320)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:152)
	at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:321)
	at org.neo4j.server.AbstractNeoServer.access$700(AbstractNeoServer.java:102)
	at org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter.start(AbstractNeoServer.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.ProcedureSignature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
2018-07-24 13:07:53.527+0000 INFO  Neo4j Server shutdown initiated by request
~~~

`Dockerfile`
~~~Dockerfile
FROM neo4j:latest

RUN apk update && apk add \
        git maven openjdk8
WORKDIR /root
RUN git clone https://github.com/neo4j-graphql/neo4j-graphql
RUN cd neo4j-graphql && \
        mvn clean package
WORKDIR /var/lib/neo4j
RUN cp /root/neo4j-graphql/target/neo4j-graphql-*.jar plugins/
RUN echo 'dbms.unmanaged_extension_classes=org.neo4j.graphql=/graphql' >> conf/neo4j.conf
~~~

Command line
~~~
docker run \
    -ti \
    --publish=7474:7474 --publish=7687:7687 \
    --env NEO4J_AUTH="neo4j/admin" \
    --ulimit=nofile=40000:40000 \
    neo4j
~~~

Can you take a look ?
Thanks !

**Comment by jexp** [comment]
Why would you clone the repository and not download the proper jar from the release instead?
You need to use the 3.4 branch. The default branch was still on 3.3 I changed that now.

**Comment by Wenzel** [comment]
Hi @jexp ,
I didn't know about the releases, i will use that from now on.

closing this issue.
