### ISSUE TITLE
kotlin.KotlinNullPointerException upon calling graphql.schema() as soon as I use a UNION type

### ISSUE THREAD

**Issue by flq** [neo4j-graphql/neo4j-graphql#188]
I suspect this can be well reproduced by providing the schema I tried:

```graphql
union Thing = ThingA | ThingB

type User {
  id: ID!
  commentsOn: [Thing!] @relation(name: "COMMENTED")
}

type ThingA {
  id: ID!
}

type ThingB {
  id: ID!
}
```

The schema is accepted wth a call to `graphql.idl` but once I call `graphql.schema` I get 

```bash
Neo.ClientError.Procedure.ProcedureCallFailed: 
Failed to invoke procedure `graphql.schema`: 
Caused by: kotlin.KotlinNullPointerException
```

I haven't tested whether other operations work but would open a different issue in that case, as this one is only related to `graphql.schema()`

**Comment by flq** [comment]
OK, the call from GraphiQL gives a bit more context:

```java
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>kotlin.KotlinNullPointerException
	at org.neo4j.graphql.GraphQLSchemaBuilder.newReferenceField(GraphQLSchemaBuilder.kt:266)
	at org.neo4j.graphql.GraphQLSchemaBuilder.addRelationships(GraphQLSchemaBuilder.kt:232)
	at org.neo4j.graphql.GraphQLSchemaBuilder.toGraphQLObjectType(GraphQLSchemaBuilder.kt:184)
	at org.neo4j.graphql.GraphQLSchemaBuilder.graphQlTypes(GraphQLSchemaBuilder.kt:682)
	at org.neo4j.graphql.GraphQLSchemaBuilder.buildSchema(GraphQLSchemaBuilder.kt:370)
	at org.neo4j.graphql.GraphQLSchemaBuilder$Companion.buildSchema(GraphQLSchemaBuilder.kt:333)
	at org.neo4j.graphql.GraphSchema.getGraphQL(GraphSchema.kt:23)
```

**Comment by jexp** [comment]
Thanks a lot also for the example. 

I don't think we added support for unions yet, we plan to do it in https://github.com/neo4j-graphql/neo4j-graphql-java and then it will be available in the plugin too.

Still needs some thinking.

/cc @conker84
