### ISSUE TITLE
Cannot find module 'neo4j-driver/lib/temporal-types'

### ISSUE THREAD

**Issue by ShuPink** [neo4j-graphql/neo4j-graphql#208]
I'm just trying to do the [graphql api quickstart](https://neo4j.com/docs/graphql-manual/current/getting-started/#_graphql_api_quick_start) and I started a project with the following as instructed: 

```
npm install @neo4j/graphql graphql neo4j-driver apollo-server
```

when I try to run the script shown in the example I get an error thrown from `DateTime.js` saying that I'm missing a module `neo4j-driver/lib/temporal-types`: 

```
// ./node_modules/@neo4j/graphql/dist/schema/scalars/DateTime.js
Object.defineProperty(exports, "__esModule", { value: true });
const graphql_1 = require("graphql");
const temporal_types_1 = require("neo4j-driver/lib/temporal-types");
```

I am actually missing this module.  When I have a look in my node_modules directory I can see that `temporal-types.js` is present in `neo4j-driver-core/lib/` not `neo4j-driver/lib/`

Have I followed the instructions incorrectly...? or am I missing something?  I'm feeling like I'm doing something really dumb.

```
// package.json

{
  "name": "example",
  "version": "1.0.0",
  "description": "this is just a test",
  "main": "index.js",
  "scripts": {
    "test": "test",
    "start": "node index.js"
  },
  "author": "shu_pink",
  "license": "ISC",
  "dependencies": {
    "@neo4j/graphql": "^1.0.1",
    "apollo-server": "^2.25.0",
    "dotenv": "^10.0.0",
    "graphql": "^15.5.0",
    "neo4j-driver": "^4.3.0"
  }
}
```

the error message: 

```
> example@1.0.0 start /home/this_user/repos/example
> node index.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'neo4j-driver/lib/temporal-types'
Require stack:
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/scalars/DateTime.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/scalars/index.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/make-augmented-schema.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/index.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/classes/index.js
- /home/this_user/repos/example/node_modules/@neo4j/graphql/dist/index.js
- /home/this_user/repos/example/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/scalars/DateTime.js:22:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/scalars/DateTime.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/scalars/index.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/make-augmented-schema.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/schema/index.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/classes/Neo4jGraphQL.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/classes/index.js',
    '/home/this_user/repos/example/node_modules/@neo4j/graphql/dist/index.js',
    '/home/this_user/repos/example/index.js'
  ]
}
```

```
// index.js
const { Neo4jGraphQL } = require("@neo4j/graphql");
const neo4j = require("neo4j-driver");
const { ApolloServer } = require("apollo-server");

const typeDefs = `
    type Movie {
        title: String
        year: Int
        imdbRating: Float
        genres: [Genre] @relationship(type: "IN_GENRE", direction: OUT)
    }

    type Genre {
        name: String
        movies: [Movie] @relationship(type: "IN_GENRE", direction: IN)
    }
`;

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("neo4j", "letmein")
);

const neoSchema = new Neo4jGraphQL({ typeDefs, driver });

const server = new ApolloServer({
    schema: neoSchema.schema,
    context: ({ req }) => ({ req }),
});

server.listen(4000).then(() => console.log("Online"));
```

**Comment by ShuPink** [comment]
Rats, sorry this is the wrong place to raise this.  I found that someone's already looking to fix this here:
[here](https://github.com/neo4j/graphql/pull/226)
