### ISSUE TITLE
Calling nested graphql queries fails at @relation

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j-graphql/neo4j-graphql#55]
My Schema:
```
interface Person {
    name: ID!
    surname: String
    born: Int
    email: [EmailAddress] @relation(name:"MAILS_TO", direction:"IN")
}
interface EmailAddress {
    address: ID!
    description: String
}
```

When I do the following graphql request the neo4j-graphql seems to fail:
```
{
  Person {
  name
  surname
  email {
    address
  }
  }
}
```

Leaving the "mail {...}" part away it works but as soon I reference to any other type/interface it fails. 
When taking the created cypher from the log file and entering it into the neo4j browser it works and I get my result displayed as expected including the email address. 

Log of my Neo4j Server:
```
{
  Person {
  name
  surname
  email {
    address
  }
  }
}
{}
MATCH (`Person`:`Person`)
RETURN labels(`Person`) AS `_labels`,
`Person`.`name` AS `name`,
`Person`.`surname` AS `surname`,
[ (`Person`)<-[:`MAILS_TO`]-(`Person_email`:`EmailAddress`)  | `Person_email` {`_labels` : labels(`Person_email`), .`address`}] AS `email`
2017-08-25 20:40:49.770+0000 ERROR The RuntimeException could not be mapped to a response, re-throwing to the HTTP container graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLObjectType
java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLObjectType
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:167)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:237)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:140)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:120)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:19)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:184)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:237)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:140)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:120)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:19)
	at graphql.execution.Execution.executeOperation(Execution.java:106)
	at graphql.execution.Execution.execute(Execution.java:49)
	at graphql.GraphQL.execute(GraphQL.java:222)
	at graphql.GraphQL.execute(GraphQL.java:187)
	at org.neo4j.graphql.GraphQLResource.executeQuery(GraphQLResource.kt:68)
	at org.neo4j.graphql.GraphQLResource.executeOperation(GraphQLResource.kt:43)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:147)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:122)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
2017-08-25 20:40:49.771+0000 WARN  /graphql/ graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLObjectType
java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLObjectType
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:167)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:237)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:140)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:120)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:19)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:184)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:237)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:140)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:120)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:19)
	at graphql.execution.Execution.executeOperation(Execution.java:106)
	at graphql.execution.Execution.execute(Execution.java:49)
	at graphql.GraphQL.execute(GraphQL.java:222)
	at graphql.GraphQL.execute(GraphQL.java:187)
	at org.neo4j.graphql.GraphQLResource.executeQuery(GraphQLResource.kt:68)
	at org.neo4j.graphql.GraphQLResource.executeOperation(GraphQLResource.kt:43)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:147)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:122)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jexp** [comment]
You need types, not interfaces.

**Comment by steffenkoenig** [comment]
Oh, true.. 
Thats the reason why some of my other worked. 

But I was pretty sure that I have seen a result two days ago with having "Interface" ;)
